version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - app-network

  twitter_mini:
    build:
      context: .
      dockerfile: Dockerfile
    image: twitter_mini:latest
    container_name: twitter_mini
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mongodb
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db: