version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  twitter-mini:
    build:
      context: .
      dockerfile: Dockerfile
    image: twitter-mini:latest
    container_name: twitter-mini
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mongodb
    links:
      - mongodb

volumes:
  db:
