version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27016:27016"
    volumes:
      - db:/data/db

  twitter_mini:
    build:
      context: .
      dockerfile: Dockerfile
    image: twitter_mini:latest
    container_name: twitter_mini
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mongodb
    links:
      - mongodb

volumes:
  db:
